In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('alphavantage_news.csv')

In [4]:
df.shape

(212, 12)

In [3]:
list = [df.shape, df.info(), df.columns.tolist()]
for item in list:
    print(item)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ticker                   212 non-null    object
 1   title                    212 non-null    object
 2   summary                  212 non-null    object
 3   source                   212 non-null    object
 4   source_domain            212 non-null    object
 5   time_published           212 non-null    object
 6   overall_sentiment_score  212 non-null    float64
 7   overall_sentiment_label  212 non-null    object
 8   target_relevance         212 non-null    float64
 9   target_sentiment_score   212 non-null    float64
 10  event_label              212 non-null    object
 11  url                      212 non-null    object
dtypes: float64(3), object(9)
memory usage: 20.0+ KB
(212, 12)
None
['ticker', 'title', 'summary', 'source', 'source_domain', 'time_published', 'overall_sentiment_score', 'overall_sentiment_label', 'target_relevance', 'target_sentiment_score', 'event_label', 'url']

In [6]:
df.head(1)

,ticker,title,summary,source,source_domain,time_published,overall_sentiment_score,overall_sentiment_label,target_relevance,target_sentiment_score,event_label,url
0,AAPL,HLAL ETF Holdings List — NASDAQ:HLAL,The article provides a detailed list of the to...,TradingView,TradingView,2025-03-31 19:53:10,0.108949,Neutral,0.904979,0.125897,MACRO,https://www.tradingview.com/symbols/NASDAQ-HLA...

In [7]:
is_equal = df['source'].equals(df['source_domain'])
print(f'Are the columns identical{is_equal}')

Are the columns identicalTrue

In [8]:
df.drop(columns = ['source_domain'], inplace=True)

In [9]:
df.columns

Index(['ticker', 'title', 'summary', 'source', 'time_published',
       'overall_sentiment_score', 'overall_sentiment_label',
       'target_relevance', 'target_sentiment_score', 'event_label', 'url'],
      dtype='object')

In [10]:
df['url']

0      https://www.tradingview.com/symbols/NASDAQ-HLA...
1      https://www.tradingview.com/symbols/AMEX-VGT/h...
2      https://www.tradingview.com/symbols/AMEX-XLK/h...
3      https://www.tradingview.com/symbols/AMEX-VUG/h...
4      https://www.inc.com/jason-aten/the-annoying-bu...
                             ...
207    https://hbsdealer.com/ace-names-its-2024-vendo...
208    https://www.worldoil.com/news/2025/3/4/fluor-l...
209    https://www.bicmagazine.com/industry/investmen...
210    https://www.bairdmaritime.com/shipping/tankers...
211    https://www.npr.org/2025/02/27/nx-s1-5311377/v...
Name: url, Length: 212, dtype: object

In [11]:
df.head()

,ticker,title,summary,source,time_published,overall_sentiment_score,overall_sentiment_label,target_relevance,target_sentiment_score,event_label,url
0,AAPL,HLAL ETF Holdings List — NASDAQ:HLAL,The article provides a detailed list of the to...,TradingView,2025-03-31 19:53:10,0.108949,Neutral,0.904979,0.125897,MACRO,https://www.tradingview.com/symbols/NASDAQ-HLA...
1,AAPL,VGT ETF Holdings List — AMEX:VGT,This article provides a detailed list of the t...,TradingView,2025-03-31 12:38:38,0.145375,Neutral,0.881822,0.149738,MACRO,https://www.tradingview.com/symbols/AMEX-VGT/h...
2,AAPL,XLK ETF Holdings List — AMEX:XLK,This article lists the top holdings of the Sta...,TradingView,2025-03-31 09:52:18,0.037572,Neutral,0.917446,0.012678,MACRO,https://www.tradingview.com/symbols/AMEX-XLK/h...
3,AAPL,VUG ETF Holdings List — AMEX:VUG,This article provides a list of the Vanguard G...,TradingView,2025-03-31 00:10:15,0.126372,Neutral,0.734640,0.140539,MACRO,https://www.tradingview.com/symbols/AMEX-VUG/h...
4,AAPL,The Annoying Bug Making Apple Users Very Angry,Apple users are frustrated with a persistent a...,Inc.com,2025-03-29 02:30:53,-0.325358,Somewhat-Bearish,0.934578,-0.346367,PRODUCT_LAUNCH,https://www.inc.com/jason-aten/the-annoying-bu...

In [15]:
for i in range(5):
    title = df['title'].iloc[i]
    print(title)

HLAL ETF Holdings List — NASDAQ:HLAL
VGT ETF Holdings List — AMEX:VGT
XLK ETF Holdings List — AMEX:XLK
VUG ETF Holdings List — AMEX:VUG
The Annoying Bug Making Apple Users Very Angry

In [13]:
for i in range(5):
    summary = df['summary'].iloc[i]
    print(summary)

The article provides a detailed list of the top holdings for the Wahed FTSE USA Shariah ETF (HLAL) as of February 26, 2026. It includes company names, stock symbols, weight percentages, share counts, and market values for each holding. Key holdings include Apple Inc., Microsoft Corporation, and Alphabet Inc. (Class A and C).
This article provides a detailed list of the top holdings within the Vanguard Information Technology ETF (VGT) as of February 27, 2026. Key holdings include NVIDIA, Apple Inc., and Microsoft Corporation, along with their respective weight percentages, shares, and market values. The data offers insights into the fund's composition and its major technology company investments.
This article lists the top holdings of the State Street Technology Select Sector SPDR ETF (XLK) as of February 25, 2026. Key holdings include NVIDIA, Apple, Microsoft, Broadcom, and Micron Technology, detailing their weight percentage, number of shares, and market value within the ETF.
This article provides a list of the Vanguard Growth ETF (VUG) holdings as of February 27, 2026. Key holdings include NVIDIA, Apple, Microsoft, Alphabet (Class A and C), Meta Platforms, Amazon, Broadcom, Tesla, and Eli Lilly and Company. The content details the weight percentage, number of shares, and market value for each of these top companies within the ETF.
Apple users are frustrated with a persistent and unclosable notification bug related to the "Reactions" feature in macOS. The notification informs users that Reactions have been turned off by their browser, but its "x" button is non-functional, leaving the annoying message on screen. This issue highlights Apple's oversight in implementing a minor feature notification without a proper dismiss function, causing significant irritation among its user base.

In [16]:
df['ticker'].unique()

array(['AAPL', 'AMZN', 'MSFT', 'GOOGL', 'NVDA', 'META', 'TSLA', 'JPM',
       'V', 'JNJ', 'BAC', 'WMT', 'UNH', 'XOM', 'CVX'], dtype=object)

In [17]:
df.columns.tolist()

['ticker',
 'title',
 'summary',
 'source',
 'time_published',
 'overall_sentiment_score',
 'overall_sentiment_label',
 'target_relevance',
 'target_sentiment_score',
 'event_label',
 'url']

In [19]:
df.drop(columns=['url'], inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ticker                   212 non-null    object
 1   title                    212 non-null    object
 2   summary                  212 non-null    object
 3   source                   212 non-null    object
 4   time_published           212 non-null    object
 5   overall_sentiment_score  212 non-null    float64
 6   overall_sentiment_label  212 non-null    object
 7   target_relevance         212 non-null    float64
 8   target_sentiment_score   212 non-null    float64
 9   event_label              212 non-null    object
dtypes: float64(3), object(7)
memory usage: 16.7+ KB

In [1]:
df['event_label']

NameError: name 'df' is not defined