In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('alphavantage_news.csv')

In [21]:
df.shape

(150, 14)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   title                    150 non-null    object
 1   url                      150 non-null    object
 2   time_published           150 non-null    object
 3   authors                  150 non-null    object
 4   summary                  150 non-null    object
 5   banner_image             123 non-null    object
 6   source                   150 non-null    object
 7   category_within_source   150 non-null    object
 8   source_domain            150 non-null    object
 9   topics                   150 non-null    object
 10  overall_sentiment_score  150 non-null    float64
 11  overall_sentiment_label  150 non-null    object
 12  ticker_sentiment         150 non-null    object
 13  ticker                   150 non-null    object
dtypes: float64(1), object(13)
memory usage: 16.5+ KB

In [53]:
import ast
df['ticker_sentiment'] = df['ticker_sentiment'].apply(ast.literal_eval)

In [62]:
df['ticker_sentiment'][0]

[{'ticker': 'AAPL',
  'relevance_score': '1.000000',
  'ticker_sentiment_score': '-0.114048',
  'ticker_sentiment_label': 'Neutral'}]

In [64]:
scores = df['ticker_sentiment'].apply(lambda x: float(x[0]['relevance_score']))

In [73]:
print("Statistics: ", scores.describe())

Statistics:  count    150.000000
mean       0.939980
std        0.174984
min        0.301066
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: ticker_sentiment, dtype: float64

In [82]:
df['overall_sentiment_label'].describe()

count                  150
unique                   5
top       Somewhat-Bullish
freq                    64
Name: overall_sentiment_label, dtype: object

In [74]:
df['ticker_sentiment'][0]

[{'ticker': 'AAPL',
  'relevance_score': '1.000000',
  'ticker_sentiment_score': '-0.114048',
  'ticker_sentiment_label': 'Neutral'}]

In [72]:
df['ticker_sentiment'][0][0]['ticker_sentiment_label']

'Neutral'

In [85]:
sentim = df['ticker_sentiment'].apply(lambda x: str(x[0]['ticker_sentiment_label']))

In [89]:
sentim.value_counts()

ticker_sentiment
Bullish             59
Neutral             39
Somewhat-Bullish    36
Somewhat-Bearish    12
Bearish              4
Name: count, dtype: int64

In [86]:
print("Statistics: ", sentim.describe())

Statistics:  count         150
unique          5
top       Bullish
freq           59
Name: ticker_sentiment, dtype: object

In [66]:
df.shape

(150, 14)

In [92]:
df['ticker'].value_counts()

ticker
AAPL    50
AMZN    50
MSFT    50
Name: count, dtype: int64

In [93]:
df.head()

,title,url,time_published,authors,summary,banner_image,source,category_within_source,source_domain,topics,overall_sentiment_score,overall_sentiment_label,ticker_sentiment,ticker
0,"Apple Marketing Chief for Watch, AirPods, Home...",https://www.bloomberg.com/news/articles/2026-0...,2026-04-17 04:14:02,['Mark Gurman'],"Stan Ng, Apple's marketing executive for the A...",https://assets.bwbx.io/images/users/iqjWHBFdfx...,Bloomberg.com,General,Bloomberg.com,"[{'topic': 'technology', 'relevance_score': '0...",-0.109092,Neutral,"[{'ticker': 'AAPL', 'relevance_score': '1.0000...",AAPL
1,Activest Wealth Management Increases Stake in ...,https://www.harianbasis.co/en/activest-wealth-...,2026-04-16 23:10:17,['Christopher Williams'],Activest Wealth Management significantly incre...,https://cdn.harianbasis.co/media/images/2026/0...,HarianBasis.co,General,HarianBasis.co,"[{'topic': 'financial_markets', 'relevance_sco...",0.301183,Somewhat-Bullish,"[{'ticker': 'AAXJ', 'relevance_score': '1.0000...",AAPL
2,"Top Stock Reports for NVIDIA, Apple & Coca-Cola",https://sg.finance.yahoo.com/news/top-stock-re...,2026-04-16 22:36:59,['Mark Vickery'],Zacks Research Daily has released new research...,https://s.yimg.com/ny/api/res/1.2/Soiqtd2LTkNd...,Yahoo Finance Singapore,General,Yahoo Finance Singapore,"[{'topic': 'earnings', 'relevance_score': '0.9...",0.205097,Somewhat-Bullish,"[{'ticker': 'AAPL', 'relevance_score': '0.9704...",AAPL
3,"Credit Rating Agencies: Definition, factors an...",https://www.stonex.com/en-gb/business/financia...,2026-04-16 21:09:19,[],Credit rating agencies (CRAs) assess the credi...,https://marketingcenter.stonex.com/transform/a...,www.stonex.com,General,www.stonex.com,"[{'topic': 'finance', 'relevance_score': '1.00...",0.356736,Bullish,"[{'ticker': 'SNEX', 'relevance_score': '1.0000...",AAPL
4,NVIDIA tops Adams fund holdings as Q1 NAV retu...,https://www.stocktitan.net/news/ADX/adams-dive...,2026-04-16 20:39:37,[],Adams Diversified Equity Fund (ADX) announced ...,https://ml.globenewswire.com/media/MjllMGQ2ZTM...,Stock Titan,General,Stock Titan,"[{'topic': 'earnings', 'relevance_score': '0.9...",0.204819,Somewhat-Bullish,"[{'ticker': 'ADX', 'relevance_score': '1.00000...",AAPL

In [103]:
df['ticker'][1]

'AAPL'

In [106]:
df['ticker_sentiment'][1]

[{'ticker': 'AAXJ',
  'relevance_score': '1.000000',
  'ticker_sentiment_score': '0.413549',
  'ticker_sentiment_label': 'Bullish'},
 {'ticker': 'AAPL',
  'relevance_score': '0.622830',
  'ticker_sentiment_score': '0.171170',
  'ticker_sentiment_label': 'Somewhat-Bullish'}]

In [107]:
df.head(2)

,title,url,time_published,authors,summary,banner_image,source,category_within_source,source_domain,topics,overall_sentiment_score,overall_sentiment_label,ticker_sentiment,ticker
0,"Apple Marketing Chief for Watch, AirPods, Home...",https://www.bloomberg.com/news/articles/2026-0...,2026-04-17 04:14:02,['Mark Gurman'],"Stan Ng, Apple's marketing executive for the A...",https://assets.bwbx.io/images/users/iqjWHBFdfx...,Bloomberg.com,General,Bloomberg.com,"[{'topic': 'technology', 'relevance_score': '0...",-0.109092,Neutral,"[{'ticker': 'AAPL', 'relevance_score': '1.0000...",AAPL
1,Activest Wealth Management Increases Stake in ...,https://www.harianbasis.co/en/activest-wealth-...,2026-04-16 23:10:17,['Christopher Williams'],Activest Wealth Management significantly incre...,https://cdn.harianbasis.co/media/images/2026/0...,HarianBasis.co,General,HarianBasis.co,"[{'topic': 'financial_markets', 'relevance_sco...",0.301183,Somewhat-Bullish,"[{'ticker': 'AAXJ', 'relevance_score': '1.0000...",AAPL

In [112]:
df['ticker_sentiment'][4]

[{'ticker': 'ADX',
  'relevance_score': '1.000000',
  'ticker_sentiment_score': '0.046662',
  'ticker_sentiment_label': 'Neutral'},
 {'ticker': 'NVDA',
  'relevance_score': '0.875347',
  'ticker_sentiment_score': '0.336521',
  'ticker_sentiment_label': 'Somewhat-Bullish'},
 {'ticker': 'AAPL',
  'relevance_score': '0.714222',
  'ticker_sentiment_score': '0.291884',
  'ticker_sentiment_label': 'Somewhat-Bullish'},
 {'ticker': 'GOOGL',
  'relevance_score': '0.661169',
  'ticker_sentiment_score': '0.244620',
  'ticker_sentiment_label': 'Somewhat-Bullish'},
 {'ticker': 'MSFT',
  'relevance_score': '0.630647',
  'ticker_sentiment_score': '0.226598',
  'ticker_sentiment_label': 'Somewhat-Bullish'}]

# **Data has multiple tickers, so identifying the ticker with greater relevancy score is important, Moreover dropping the irrelevant ticker and getting the data from credible sources only is crucial part as well**

In [113]:
def is_relevant_to_ticker(row, ticker, min_relevance=0.5):
    for item in row['ticker_sentiment']:
        if item['ticker'] == ticker:
            return float(item['relevance_score']) >= min_relevance
    return False

df = df[df.apply(lambda row: is_relevant_to_ticker(row, row['ticker']), axis=1)]

In [117]:
df['ticker_sentiment'][2]

[{'ticker': 'AAPL',
  'relevance_score': '0.970455',
  'ticker_sentiment_score': '0.344899',
  'ticker_sentiment_label': 'Somewhat-Bullish'},
 {'ticker': 'NVDA',
  'relevance_score': '0.922239',
  'ticker_sentiment_score': '0.277328',
  'ticker_sentiment_label': 'Somewhat-Bullish'},
 {'ticker': 'KO',
  'relevance_score': '0.920552',
  'ticker_sentiment_score': '0.120729',
  'ticker_sentiment_label': 'Neutral'},
 {'ticker': 'JBL',
  'relevance_score': '0.606687',
  'ticker_sentiment_score': '0.217162',
  'ticker_sentiment_label': 'Somewhat-Bullish'},
 {'ticker': 'PFE',
  'relevance_score': '0.550575',
  'ticker_sentiment_score': '0.114757',
  'ticker_sentiment_label': 'Neutral'}]

In [124]:
df['ticker'].unique()

array(['AAPL', 'AMZN', 'MSFT'], dtype=object)

In [125]:
mask = df.apply(lambda row: is_relevant_to_ticker(row, row['ticker']), axis=1)
print(mask.value_counts())

True    150
Name: count, dtype: int64

In [131]:
for i in range(5):
    # for j in range(df['ticker_sentiment']):
    print(df['ticker_sentiment'][i])

[{'ticker': 'AAPL', 'relevance_score': '1.000000', 'ticker_sentiment_score': '-0.114048', 'ticker_sentiment_label': 'Neutral'}]
[{'ticker': 'AAXJ', 'relevance_score': '1.000000', 'ticker_sentiment_score': '0.413549', 'ticker_sentiment_label': 'Bullish'}, {'ticker': 'AAPL', 'relevance_score': '0.622830', 'ticker_sentiment_score': '0.171170', 'ticker_sentiment_label': 'Somewhat-Bullish'}]
[{'ticker': 'AAPL', 'relevance_score': '0.970455', 'ticker_sentiment_score': '0.344899', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'NVDA', 'relevance_score': '0.922239', 'ticker_sentiment_score': '0.277328', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'KO', 'relevance_score': '0.920552', 'ticker_sentiment_score': '0.120729', 'ticker_sentiment_label': 'Neutral'}, {'ticker': 'JBL', 'relevance_score': '0.606687', 'ticker_sentiment_score': '0.217162', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'PFE', 'relevance_score': '0.550575', 'ticker_sentiment_score': '0.114757', 'ticker_sentiment_label': 'Neutral'}]
[{'ticker': 'SNEX', 'relevance_score': '1.000000', 'ticker_sentiment_score': '0.330806', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'MCO', 'relevance_score': '0.926992', 'ticker_sentiment_score': '0.309580', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'SPGI', 'relevance_score': '0.894381', 'ticker_sentiment_score': '0.329696', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'AAPL', 'relevance_score': '0.730756', 'ticker_sentiment_score': '0.389030', 'ticker_sentiment_label': 'Bullish'}, {'ticker': 'MS', 'relevance_score': '0.638385', 'ticker_sentiment_score': '0.341033', 'ticker_sentiment_label': 'Somewhat-Bullish'}]
[{'ticker': 'ADX', 'relevance_score': '1.000000', 'ticker_sentiment_score': '0.046662', 'ticker_sentiment_label': 'Neutral'}, {'ticker': 'NVDA', 'relevance_score': '0.875347', 'ticker_sentiment_score': '0.336521', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'AAPL', 'relevance_score': '0.714222', 'ticker_sentiment_score': '0.291884', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'GOOGL', 'relevance_score': '0.661169', 'ticker_sentiment_score': '0.244620', 'ticker_sentiment_label': 'Somewhat-Bullish'}, {'ticker': 'MSFT', 'relevance_score': '0.630647', 'ticker_sentiment_score': '0.226598', 'ticker_sentiment_label': 'Somewhat-Bullish'}]

In [132]:
df.shape

(150, 14)